### ISSUE TITLE
lbh: 希望能更改文字颜色

### ISSUE THREAD

**Issue by zhc7** [JingBh/zgk-avatar#2]
![image](https://user-images.githubusercontent.com/53651354/119225538-ec2e0880-bb36-11eb-832c-9c5c94aefa6b.png)

虽然我觉得这个大概率是不会做了，但我还是帮他提一下吧

**Comment by JingBh** [comment]
先 Close 了

**Comment by zhc7** [comment]
![image](https://user-images.githubusercontent.com/53651354/119226627-ae33e300-bb3c-11eb-83da-55c63ca14c8c.png)
